<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Mimir.App</AssemblyName>
    <RootNamespace>Mimir.App</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mimir.Runtime\Mimir.Runtime.csproj" />
    <ProjectReference Include="..\..\..\Aquarium-Engine\src\Aquarium.Engine\Aquarium.Engine.csproj" />
  </ItemGroup>

</Project>
